### ISSUE TITLE
Add `gzip` as a build dependency to the AUR package

### ISSUE THREAD

**Issue by chuck-flowers** [chuck-flowers/humble-lumpia#11]
The repository has been updated to install a man page as well. Part of this man page installation requires compressing the troff file using `gzip`. The package's build dependencies should be update to reflect this.

**Comment by NINNiT** [comment]
I will update the AUR package later today and test it, thanks for the notice!

**Comment by chuck-flowers** [comment]
@NINNiT what's a good way for me to coordinate these types of changes with you in the future?

**Comment by NINNiT** [comment]
@chuck-flowers I think creating an issue and assigning me will suffice, as i'll receive a notification on all of my devices.

**Comment by chuck-flowers** [comment]
You don't seem to show up in the list of assignable users for a new issue. I can only assign issues to you if you're already participating in them. Do you know what I need to do for you to appear as an option on a new issue?

**Comment by NINNiT** [comment]
I think you may need to manually grant me access in the repos settings as I've not contributed any actual code yet and I am therefore not automatically being flagged as a contributor. 

Alternatively, maybe a simple ping using @NINNiT in the issue message should work too, or an email to the address defined in the PKGBUILD (soelder@hotmail.com), although i think that the git way is the cleanest.

**Comment by NINNiT** [comment]
I'll push the newest PKGBUILD later today.
`gzip` has been added as a build dependency. 

I've also thought about adding `man-db`, however I'm not sure if that should be an optional or required dependency?
@chuck-flowers

**Comment by chuck-flowers** [comment]
@NINNiT I don't think `man-db` should be added as an optional dependency. Most packages don't include `man` as a dependency just because they provided man pages. For example [iproute2](https://archlinux.org/packages/core/x86_64/iproute2/) doesn't mention man anywhere even though it provides man pages. If man is installed, then our man pages will be available for consumption. If man isn't installed, then our pages are benign and won't do any harm.

**Comment by NINNiT** [comment]
New `PKGBUILD` is now live.
