### ISSUE TITLE
AUR package: `makepkg` fails due to changes in Makefile

### ISSUE THREAD

**Issue by NINNiT** [chuck-flowers/humble-lumpia#12]
Since the recent updates to the `Makefile`, `makepkg` fails to build humble-lumpia.
I think the problem is due to potentially missing directories in the destination path of the `install -Dm444` commands and it seems that `install -Dm444` does not automatically create the defined path.

I've stumpled upon this stackoverflow [post](https://stackoverflow.com/questions/39892692/how-to-implement-make-install-in-a-makefile/39895302). Using `install -d` (checks if path exists and if not, creates it) and `install -m` separately fixes the problem and works for the manual installation and the AUR package.

The `DESTDIR` environment variable was also added: [ArchWiki](https://wiki.archlinux.org/title/creating_packages#package())

**Comment by chuck-flowers** [comment]
Excellent write up and I appreciate all the articles you linked. Your pull request works for me. I'll take one last look at it in the morning and accept it.
