### ISSUE TITLE
mention version that was installed when installing latest

### ISSUE THREAD

**Issue by thibaultmol** [chuck-flowers/humble-lumpia#14]
Hi, I'm wondering if it's possible to mention the version that is being installed when you do 
humble-lumpia install latest
Because now it just says that it installed 'it'. But would be nice if you could see the actual version right there in the output of that command.

(thx for making this tool, it's very convenient)

**Comment by thibaultmol** [comment]
Yeah, forgot it was a git package

I guess if `install latest` is run, then it should check.
if `install x.x-GE-x` is run, it should only check if it doesn't see the version number in it's release file.

**Comment by chuck-flowers** [comment]
That seems reasonable to me. I'll work on adding that soon.

**Comment by chuck-flowers** [comment]
@thibaultmol I pushed a new commit to master with the auto-refreshing behavior you described
