### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by NINNiT** [chuck-flowers/humble-lumpia#5]
Hi,

I've created an AUR package for easy humble-lumpia package management for ArchLinux users: [AUR](https://aur.archlinux.org/packages/humble-lumpia-git/).

Just FYI, whether or not you want to add it to the README is up to you :-) 
Installation can be done e.g. with an AUR helper like `yay` using `yay -S humble-lumpia-git`.

Thanks for the nice software! 

NINNiT

**Comment by chuck-flowers** [comment]
Hey thanks for the contribution. I'll take a look and give you some feedback once I have some time and if I see anything I think should be updated, I'll let you know. Once any issues are taken care of, I'd be happy to add it as an installation option in the README with a mention to you.

**Comment by lpww** [comment]
@chuck-flowers I agree that `humble-lumpia` should not install Proton's dependencies. It would be difficult or impossible to account for all the different package managers out there.

However, I do think there is a case for the AUR package to include the proton dependencies. This [GE package](https://aur.archlinux.org/packages/proton-ge-custom-bin/) includes the proton dependencies. Most of them are optional with a note about when you might need them. I think this would be a good approach for the `humble-lumpia` AUR package and would improve the installation experience

**Comment by NINNiT** [comment]
@chuck-flowers `curl` and `jq` are definitely dependencies which should get installed with the AUR package as it's strictly necessary to run the software. 

@lpww  I do agree that there really is a case to offer them as optional dependencies. I guess the majority of users coming to humble-lumpia already have a working proton (-ge) installation, but it wouldn't hurt to offer them within the AUR package. 

Maybe the humble-lumpia README could also refer to the [proton-ge-repo](https://github.com/GloriousEggroll/proton-ge-custom#installation) or at least tell users that they have to install the proton dependencies prior to using humble-lumpia.

Thanks for the input, i'll update the PKGBUILD as soon as i have time and let you guys know! :+1:

**Comment by lpww** [comment]
Thanks @NINNiT ! I agree that updating the `humble-lumpia` README to mention proton dependencies would be a good idea.

**Comment by NINNiT** [comment]
I've updated the AUR package. 

It now contains `curl` and `jq` as dependencies, as well as all (optional) dependencies needed for proton-ge-custom. For the latter, I've basically used the same as the AUR package linked above by @lpww.

**Comment by lpww** [comment]
The new dependencies look good! It makes sense that the dependencies from the other GE package can be used here. I'll give it a test run later tonight

**Comment by chuck-flowers** [comment]
I'll also try it out shortly. Just recently switched to Arch and I haven't installed this project form the AUR yet so I'm interested in seeing what the user experience is like.

**Comment by chuck-flowers** [comment]
@NINNiT  I tried installing from the AUR package and it seems to work well. The only question I had was why `vulkan-icd-loader` seems to be marked as a required dependency? Shouldn't it be optional like the rest of the proton dependencies or am I reading something incorrectly?

I've created a PR for updating the README. If either of you have time, feel free to read over the new changes to the README, and give me any feedback on the wording or something additional that should be added.

**Comment by NINNiT** [comment]
@chuck-flowers Thanks for taking another look! I've added `python` and `vulkan-icd-loader` as required dependencies, following the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=proton-ge-custom-bin) of `proton-ge-custom-bin` which seems to imply that those are strictly needed for running GloriousEggroll's proton builds. Contrary to the optional dependencies, which might offer better performance and user experience but are maybe not directly necessary to get a working proton installation (e.g fsync-patched kernels, xbox controller driver,...). 

PR looks good! :100:

**Comment by chuck-flowers** [comment]
Okay thanks for looking at the PR. We can leave the AUR package as is. I'll merge the PR at the end of the day to allow for any other comments to be made.

**Comment by lpww** [comment]
According to the [Arch Wiki](https://wiki.archlinux.org/title/Vulkan), `vulkan-icd-loader` (and vulkan graphics drivers) are required to run vulkan programs. A fair amount of games are using Vulkan at this point, so I think it makes sense for it to be a required dependency.

`python` I am not sure sure about but it's probably safe to assume that if it's required for `proton-ge-custom-bin`, it is probably required for `humble-lumpia-git`.

I updated my system and saw logs about the optional dependencies. It seems to be working!

**Comment by NINNiT** [comment]
I've done a bit of digging, seems that the [proton start script](https://github.com/GloriousEggroll/proton-ge-custom/blob/master/proton) itself and a few more scripts are using python.

**Comment by chuck-flowers** [comment]
I think the vast majority of people who are going to use this will likely already have `steam` installed so we can leave the AUR package as declared for now and revisit the dependencies once the project is stable and we are getting ready to make a `humble-lumpia` (non git) AUR package available.

**Comment by chuck-flowers** [comment]
@NINNiT, sorry to necro this issue but I don't have another way to contact you currently. I made an update to the repo that will require a new build dependency in the AUR package. I added man pages to the project and `gzip` is necessary now. The relevant issue is #11.
